import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {Database,Disc3,HardDrive,Server,Activity,Box,Settings,Network,Archive,ShieldCheck} from 'lucide-react'; import './style.css';
type Page='Dashboard'|'Media'|'Build'|'Bare Metal'|'PXE'|'Jobs'|'Storage'|'Administration';
const nav:[Page,any][]=[['Dashboard',Activity],['Media',Disc3],['Build',Box],['Bare Metal',HardDrive],['PXE',Network],['Jobs',Archive],['Storage',Database],['Administration',Settings]];
function App(){const [page,setPage]=useState<Page>('Dashboard'); const [health,setHealth]=useState<any>(null); const [jobs,setJobs]=useState<any[]>([]); const [media,setMedia]=useState<any[]>([]); const [stores,setStores]=useState<any[]>([]);
 const refresh=()=>{fetch('/api/v1/health').then(r=>r.json()).then(setHealth).catch(()=>{}); fetch('/api/v1/jobs').then(r=>r.json()).then(setJobs).catch(()=>{}); fetch('/api/v1/media').then(r=>r.json()).then(setMedia).catch(()=>{}); fetch('/api/v1/storage').then(r=>r.json()).then(setStores).catch(()=>{});}; useEffect(()=>{refresh(); const t=setInterval(refresh,5000); return()=>clearInterval(t)},[]);
 return <div className="app"><aside><div className="brand"><ShieldCheck size={26}/><div><b>Bare-Metal Adapter</b><span>Deployment Management</span></div></div>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}</button>)}<div className="status"><span className={health?'dot ok':'dot'}></span>{health?'Appliance online':'Connecting…'}</div></aside><main><header><div><h1>{page}</h1><p>Self-hosted bare-metal deployment and media adaptation</p></div><button className="outline" onClick={refresh}>Refresh</button></header>{page==='Dashboard'&&<Dashboard media={media} jobs={jobs} stores={stores}/>} {page==='Media'&&<MediaPage media={media} stores={stores} refresh={refresh}/>} {page==='Jobs'&&<JobsPage jobs={jobs}/>} {page==='Storage'&&<StoragePage stores={stores} refresh={refresh}/>} {!['Dashboard','Media','Jobs','Storage'].includes(page)&&<Future page={page}/>}</main></div>}
function Dashboard({media,jobs,stores}:any){return <><div className="cards"><Card t="Media objects" v={media.length}/><Card t="Storage locations" v={stores.length}/><Card t="Active jobs" v={jobs.filter((x:any)=>['queued','running'].includes(x.status)).length}/><Card t="Completed" v={jobs.filter((x:any)=>x.status==='complete').length}/></div><section><h2>Platform architecture</h2><div className="capgrid"><Cap t="External-first storage" d="ISOs, golden images and drivers stay on mounted SMB/NFS storage."/><Cap t="ISO adapter engine" d="ISO9660, El Torito, EFI, Casper, GRUB, ISOLINUX and Windows media detection."/><Cap t="Golden images" d="Capture/deployment subsystem is scaffolded for filesystem-aware, WIM and raw imaging."/><Cap t="Heimdal PXE bridge" d="Current Stage-1 WinPE to UEFI handoff remains the first integration adapter."/></div></section></>}
const Card=({t,v}:any)=><div className="card"><span>{t}</span><strong>{v}</strong></div>; const Cap=({t,d}:any)=><div className="cap"><b>{t}</b><p>{d}</p></div>;
function MediaPage({media,stores,refresh}:any){
 const [sid,setSid]=useState(''); const [path,setPath]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!sid&&stores.length)setSid(String(stores[0].id))},[stores]);
 const analyze=async()=>{if(!sid||!path)return; setBusy(true); await fetch('/api/v1/media/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storage_id:Number(sid),relative_path:path})}); setBusy(false); alert('Analysis job queued'); refresh();};
 const upload=async()=>{if(!sid||!file)return; setBusy(true); const fd=new FormData(); fd.append('file',file); const r=await fetch(`/api/v1/media/upload?storage_id=${sid}`,{method:'POST',body:fd}); const d=await r.json(); setBusy(false); if(!r.ok){alert(d.detail||'Upload failed');return;} setPath(d.relative_path); alert(`Stored ${d.name} on external storage. You can analyze it now.`);};
 return <><section><h2>Import media</h2><p className="muted">Browser uploads stream directly to the selected external storage location; the appliance does not retain a second media copy.</p><div className="toolbar"><select value={sid} onChange={e=>setSid(e.target.value)}>{stores.map((s:any)=><option value={s.id}>{s.name} — {s.path}</option>)}</select><input type="file" accept=".iso" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={busy||!file} onClick={upload}>{busy?'Working…':'Upload ISO'}</button></div></section><section><h2>Analyze existing media</h2><div className="toolbar"><select value={sid} onChange={e=>setSid(e.target.value)}>{stores.map((s:any)=><option value={s.id}>{s.name}</option>)}</select><input className="grow" placeholder="Relative path, e.g. ubuntu.iso" value={path} onChange={e=>setPath(e.target.value)}/><button disabled={busy||!path} onClick={analyze}>Analyze ISO</button></div><table><thead><tr><th>Name</th><th>Type</th><th>Size</th><th>Adapter</th><th>SHA-256</th></tr></thead><tbody>{media.map((m:any)=><tr><td>{m.name}</td><td>{m.media_type}</td><td>{(m.size_bytes/1073741824).toFixed(2)} GiB</td><td>{m.analysis?.recommended_adapter||'—'}</td><td className="mono">{m.sha256?.slice(0,16)||'—'}…</td></tr>)}</tbody></table></section></>}
function JobsPage({jobs}:any){return <section>{jobs.length===0?<div className="empty">No jobs yet.</div>:jobs.map((j:any)=><div className="job"><div><b>#{j.id} {j.kind}</b><span>{j.status}</span></div><div className="progress"><i style={{width:`${j.progress}%`}}/></div><pre>{j.log}</pre></div>)}</section>}
function StoragePage({stores,refresh}:any){const [name,setName]=useState(''); const [path,setPath]=useState('/storage/iso'); const add=async()=>{await fetch('/api/v1/storage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,path,kind:'mounted',role:'media'})}); setName(''); refresh();}; return <><section><h2>External storage locations</h2><p className="muted">Mount SMB/NFS shares on the appliance and register their mounted paths here. Media remains on the share.</p><div className="toolbar"><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input className="grow" value={path} onChange={e=>setPath(e.target.value)}/><button onClick={add}>Add storage</button></div>{stores.map((s:any)=><div className="storage"><Server size={20}/><div><b>{s.name}</b><span>{s.path}</span></div><em>{s.kind}</em></div>)}</section></>}
function Future({page}:any){return <section className="future"><Box size={44}/><h2>{page}</h2><p>The subsystem is included in the platform architecture and data model. Its workflow will be enabled as the corresponding engine is implemented.</p></section>}
createRoot(document.getElementById('root')!).render(<App/>);
